<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>1d9c79b1-7199-47dc-8e74-261de0c86bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/section/main/div/div/section[4]/div/div/div[1]/div/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/section/main/div/div/section[4]/div/div/div[1]/div/a[1]</value>
      <webElementGuid>980a0df8-5162-41a6-9fe4-26aa366305c0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
