<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>628da08e-e109-44fc-9804-e58f9fa6c772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[title=&quot;06/10/2023&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='06/10/2023']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af7cba3c-9f6e-4713-a53d-f2697245221e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>1bb0e6df-e9cb-4f44-9fe4-b8504e8e6989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>06/10/2023</value>
      <webElementGuid>cce7ecea-46d7-4f16-9a99-7e3322a854c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>e498ca1a-0318-42ea-92d1-de8d9117fd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e239e580-8115-45a7-8aea-a1c0234c7373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>06/10/2023</value>
      <webElementGuid>a7182b56-0344-4bc2-b0dd-251bd3a86d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout min-w-screen min-h-screen&quot;]/main[@class=&quot;ant-layout-content bg-gray-10&quot;]/div[@class=&quot;webapp-content-layout&quot;]/div[@class=&quot;webapp-content&quot;]/div[@class=&quot;add-schedule-screen&quot;]/div[@class=&quot;form-plc&quot;]/div[@class=&quot;form-personal-event&quot;]/div[@class=&quot;mt-4 flex&quot;]/div[@class=&quot;date-picker&quot;]/div[@class=&quot;py-2&quot;]/div[@class=&quot;ant-picker w-full text-4 border border-solid border-ash-800 rounded-4 py-2.5 px-3&quot;]/div[@class=&quot;ant-picker-input&quot;]/input[1]</value>
      <webElementGuid>43e20327-415a-4e97-9c25-a1eb5a480423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='06/10/2023']</value>
      <webElementGuid>80f9f6b3-20b6-4159-8265-6b52041a3d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/div/div[2]/div/div[2]/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>02bcb6f4-fe53-424e-987b-ed45b966d73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>8af85050-4f03-4963-bea7-668b8776fe69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'DD/MM/YYYY' and @title = '06/10/2023']</value>
      <webElementGuid>75e85b32-4365-4891-8132-21bc7e7639b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
