<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Upload Image_react-sketch-canvas__canvas-background</name>
   <tag></tag>
   <elementGuidId>83d6bca9-6590-481b-9e63-17a816ae9d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-sketch-canvas__canvas-background</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//rect[@id = 'react-sketch-canvas__canvas-background']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>f4c61ad3-e622-469a-b832-763c3e202735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-sketch-canvas__canvas-background</value>
      <webElementGuid>f19f961f-9c4e-4fb9-b114-244f16f29890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3d548411-07d5-4149-8b7a-3baf6f883852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>acc90033-1c6b-4d5a-b90f-93241819da6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>2611ab42-862d-4e4c-a656-9156c1012c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>7644b903-506d-4191-bd20-2148985d89e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>d6b730e3-5939-4b2f-b57f-63b72d53fd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-sketch-canvas__canvas-background&quot;)</value>
      <webElementGuid>52501929-aaf6-4d7b-bce1-88617ac7e5a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rect[@id = 'react-sketch-canvas__canvas-background']</value>
      <webElementGuid>0fd7d693-6f22-46ac-a8a2-8599f4c5c2f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
