<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Upload Image</name>
   <tag></tag>
   <elementGuidId>42bf0b36-0e70-4a74-a52f-4cb496d09ca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/main/div/div[2]/div/div/div[3]/div[7]/div[2]/form/div[2]/div/div[2]/div/div/div[2]/div/label[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/section/main/div/div[2]/div/div/div[3]/div[7]/div[2]/form/div[2]/div/div[2]/div/div/div[2]/div/label[2]/span[1]/input</value>
      <webElementGuid>4b98dd56-ad7e-4577-9de9-43e9b96f09f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/div/div[2]/div/div/div[3]/div[7]/div[2]/form/div[2]/div/div[2]/div/div/div[2]/div/label[2]/span[2]</value>
      <webElementGuid>15ee1056-edfe-4558-b971-f5d08c6840c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In App Signature'])[1]/following::span[3]</value>
      <webElementGuid>7f6f2e69-ffc3-439e-b564-af8c01b5bdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can choose wether create signature in app or upload signature image'])[1]/following::span[6]</value>
      <webElementGuid>2b8458e8-7940-4855-a31d-116195ba4c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::span[1]</value>
      <webElementGuid>520f7a59-c6cf-40a9-b790-73f9c8e4094b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Signature'])[1]/preceding::span[2]</value>
      <webElementGuid>9a311f61-1272-4472-b5cf-c426ea3567a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload Image']/parent::*</value>
      <webElementGuid>77873486-e749-4073-ac7a-e3f92f838e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span[2]</value>
      <webElementGuid>a9f0daf3-c05a-433a-be62-bca62dc76f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Upload Image' or . = 'Upload Image')]</value>
      <webElementGuid>c993540f-6afa-4224-81c5-f319c3af155f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
